//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LazyLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2006=复活术
        ///2008=先祖之魂
        ///2018=锻造
        ///2020=初级锻造
        ///2021=中级锻造
        ///2023=恢复法力
        ///2024=治疗药水
        ///2050=治疗术
        ///2060=强效治疗术
        ///2061=快速治疗
        ///2062=土元素图腾
        ///2075=灼热图腾
        ///2094=致盲
        ///2096=心灵视界
        ///2098=刺骨
        ///2108=制皮
        ///2110=FIRESTAFF (DND)
        ///2118=躲闪精通
        ///2119=自然抗性
        ///2120=烈焰风暴
        ///2123=神圣亲和
        ///2124=烈焰风暴
        ///2125=烈焰风暴
        ///2136=火焰冲击
        ///2139=法术反制
        ///2140=静电效果
        ///2141=火焰冲击
        ///2142=火焰冲击
        ///2143=火焰冲击
        ///2147=治疗
        ///2148=周期性暗影风暴
        ///2149=手工皮靴
        ///2152=轻型护甲片
        ///2153=手工皮短裤
        ///2154=中级制皮
        ///2155=初级制皮
        ///2156=轻便冬季披风
        ///2157=轻便冬季长靴
        ///2158=优质皮靴
        ///2159=优质皮披风
        ///2160=雕花皮外衣
        ///2161=雕花皮靴
        ///2162=雕花皮质披风
        ///2163=白色皮夹克
        ///2164=优质皮手套
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
    }
}
