//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LazyLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2006=复活术
        ///2008=先祖之魂
        ///2018=锻造
        ///2020=初级锻造
        ///2021=中级锻造
        ///2023=恢复法力
        ///2024=治疗药水
        ///2050=治疗术
        ///2060=强效治疗术
        ///2061=快速治疗
        ///2062=土元素图腾
        ///2075=灼热图腾
        ///2094=致盲
        ///2096=心灵视界
        ///2098=刺骨
        ///2108=制皮
        ///2110=FIRESTAFF (DND)
        ///2118=躲闪精通
        ///2119=自然抗性
        ///2120=烈焰风暴
        ///2123=神圣亲和
        ///2124=烈焰风暴
        ///2125=烈焰风暴
        ///2136=火焰冲击
        ///2139=法术反制
        ///2140=静电效果
        ///2141=火焰冲击
        ///2142=火焰冲击
        ///2143=火焰冲击
        ///2147=治疗
        ///2148=周期性暗影风暴
        ///2149=手工皮靴
        ///2152=轻型护甲片
        ///2153=手工皮短裤
        ///2154=中级制皮
        ///2155=初级制皮
        ///2156=轻便冬季披风
        ///2157=轻便冬季长靴
        ///2158=优质皮靴
        ///2159=优质皮披风
        ///2160=雕花皮外衣
        ///2161=雕花皮靴
        ///2162=雕花皮质披风
        ///2163=白色皮夹克
        ///2164=优质皮手套
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4922,暮光高地
        ///4815,柯尔普萨之森
        ///5144,烁光海床
        ///5146,瓦丝琪尔
        ///4080,奎尔丹纳斯岛
        ///4,诅咒之地
        ///4298,东瘟疫之地：血色领地
        ///25,黑石山
        ///41,逆风小径
        ///46,燃烧平原
        ///51,灼热峡谷
        ///139,东瘟疫之地
        ///3,荒芜之地
        ///8,悲伤沼泽
        ///28,西瘟疫之地
        ///47,辛特兰
        ///5287,荆棘谷海角
        ///5339,荆棘谷
        ///11,湿地
        ///33,北荆棘谷
        ///45,阿拉希高地
        ///10,暮色森林
        ///267,希尔斯布莱德丘陵
        ///44,赤脊山
        ///4706,吉尔尼斯废墟
        ///38,洛克莫丹
        ///40,西部荒野
        ///130,银松森林
        ///3433,幽魂之地
        ///1,丹莫罗
        ///12,艾尔文森林
        ///85,提瑞斯法林地
        ///1497,幽暗城
        ///1519,暴风城
        ///1537,铁炉堡
        ///3430,永歌森林
        ///3487,银月城
        ///4714,吉尔尼斯
        ///4755,吉尔尼斯城
        ///5095,托尔巴拉德
        ///5042,深岩之洲
        ///4720,失落群岛
        ///4737,科赞
        ///5416,大漩涡
        ///3520,影月谷
        ///3523,虚空风暴
        ///3522,刀锋山
        ///3518,纳格兰
        ///3519,泰罗卡森林
        ///3521,赞加沼泽 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZoneText {
            get {
                return ResourceManager.GetString("ZoneText", resourceCulture);
            }
        }
    }
}
